Repository spoteditor/Spoteditor-Frontend, pull requests merged in 2025-03, with the labels that each got.

#36 dev/로그 등록, 쿼리 데이터 연결
  package.json
  src/App.tsx
  src/components/Pagination/MainPagination.tsx
  src/components/ui/pagination.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/LogCard.tsx
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/features/registerpage/SearchPlacesDrawer.tsx
  src/hooks/queries/log/logQueryKeys.ts
  src/hooks/queries/log/useLog.tsx
  src/hooks/queries/log/useLogList.tsx
  src/hooks/useImagePreview.tsx
  src/hooks/useImages.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/register/DetailsPage.tsx
  src/pages/register/WritePage.tsx
  src/pages/register/index.tsx
  src/routes/router.tsx
  src/services/apis/api.ts
  src/services/apis/logApi.ts
  src/services/apis/registerApi.ts
  src/services/apis/types/logAPI.type.ts
  src/services/apis/types/registerAPI.type.ts
  yarn.lock
Labels: ✨ 기능추가

#37 로그 등록, 쿼리 데이터 연결
  package.json
  src/App.tsx
  src/components/Pagination/MainPagination.tsx
  src/components/ui/pagination.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/LogCard.tsx
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/features/registerpage/SearchPlacesDrawer.tsx
  src/hooks/queries/log/logQueryKeys.ts
  src/hooks/queries/log/useLog.tsx
  src/hooks/queries/log/useLogList.tsx
  src/hooks/useImagePreview.tsx
  src/hooks/useImages.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/register/DetailsPage.tsx
  src/pages/register/WritePage.tsx
  src/pages/register/index.tsx
  src/routes/router.tsx
  src/services/apis/api.ts
  src/services/apis/logApi.ts
  src/services/apis/registerApi.ts
  src/services/apis/types/logAPI.type.ts
  src/services/apis/types/registerAPI.type.ts
  yarn.lock
Labels: ✨ 기능추가, 🚀 배포

#38 배포 에러 수정
  vite.config.ts
Labels: 🐛 버그수정, 🚀 배포

#39 홈 화면 콘텐츠에 옵셔널 체이닝과 널리시 콜리시 적용
  src/pages/home/HomePage.tsx
Labels: 🐛 버그수정, 🚀 배포

#40 로그리스트 데이터 기본값 적용
  src/pages/home/HomePage.tsx
Labels: 🐛 버그수정, 🚀 배포

#41 홈 배열 메소드에 옵셔널 체이닝 적용
  src/pages/home/HomePage.tsx
Labels: 🐛 버그수정, 🚀 배포

#43 폴리싱 작업 및 등록페이지에 위치동의 모달창 추가
  src/assets/homepage/global.png
  src/components/CustomPagination.tsx
  src/components/GeoConsentModal.tsx
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Header/SectionHeader.tsx
  src/components/Icons/EarthIcon.tsx
  src/components/Icons/index.ts
  src/components/ui/dialog.tsx
  src/features/homepage/CitySearchButton.tsx
  src/features/homepage/CitySearchForm.tsx
  src/features/notice/NoticeHeader.tsx
  src/features/notice/notice-detail/NoticeDetailContent.tsx
  src/features/notice/notice-detail/NoticeDetailHeader.tsx
  src/features/profile/FollowButton.tsx
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TabNavButton.tsx
  src/features/search/SearchBar.tsx
  src/features/search/SearchTitleHeader.tsx
  src/hooks/useGeolocationPermission.tsx
  src/index.css
  src/layouts/ContentLayout.tsx
  src/layouts/MainLayout.tsx
  src/layouts/PageLayout.tsx
  src/layouts/RegisterLayout.tsx
  src/pages/notice/index.tsx
  src/pages/notice/notice-detail/index.tsx
  src/pages/search/index.tsx
Labels: ✨ 기능추가, 🎨디자인수정

#44 프로필 관련 폴리싱 작업
  src/components/Header/MainHeader/LoginStatusButtons.tsx
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Header/MainHeader/components/LoginButton.tsx
  src/components/Header/MainHeader/components/LoginStatusButtons.tsx
  src/components/Header/MainHeader/components/SearchBarButton.tsx
  src/components/Header/MainHeader/components/UserProfileButton/MyProfileButton.tsx
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
  src/features/profile-setting/AccountSettings.tsx
  src/features/profile-setting/ProfileSettingAvatar.tsx
  src/features/profile-setting/ProfileSettingForm/ProfileSettingForm.tsx
  src/features/profile-setting/ProfileSettingForm/TextCounter.tsx
  src/features/profile/LogoutButton.tsx
  src/features/profile/LogoutConfirmButton.tsx
  src/hooks/queries/user/userQueryKeys.ts
  src/hooks/useResponsive.tsx
  src/hooks/useUser.tsx
  src/pages/profile-setting/index.tsx
  src/routes/router.tsx
  src/services/apis/authApi.ts
  src/services/apis/types/userAPI.type.ts
  src/services/apis/userApi.ts
  src/services/schemas/profileSchema.ts
Labels: ✨ 기능추가, 🐛 버그수정, 🎨디자인수정

#46 배포 에러 수정
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
Labels: 🐛 버그수정, 🚀 배포

#48 메인페이지 수정 및 Skeleton 적용
  src/components/Icons/ArrowIcon.tsx
  src/components/Icons/CameraIcon.tsx
  src/components/Icons/EarthIcon.tsx
  src/components/Icons/LeftArrowIcon.tsx
  src/components/Icons/SettingIcon.tsx
  src/components/Icons/TableIcon.tsx
  src/components/Skeleton/LogCardSkeleton.tsx
  src/components/Skeleton/LogCoverSkeleton.tsx
  src/components/Skeleton/PlaceItemSkeleton.tsx
  src/components/ui/dialog.tsx
  src/components/ui/skeleton.tsx
  src/contexts/KakaoMap.context.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/CursorBlinker.tsx
  src/features/homepage/LogCard.tsx
  src/features/homepage/MainHero.tsx
  src/features/homepage/TypingText.tsx
  src/hooks/queries/log/useLog.ts
  src/hooks/queries/log/useLogList.ts
  src/index.css
  src/layouts/RegisterLayout.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/detail/PlacesCollectionPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/register/MapPage.tsx
  src/routes/router.tsx
  src/services/apis/logApi.ts
  src/services/apis/types/logAPI.type.ts
Labels: 🔨 리팩토링, 🎨디자인수정

#49 폴리싱 작업 및 기능 추가 배포
  src/components/GeoConsentModal.tsx
  src/components/Header/MainHeader/components/LoginStatusButtons.tsx
  src/components/Header/MainHeader/components/UserProfileButton/MyProfileButton.tsx
  src/components/Icons/ArrowIcon.tsx
  src/components/Icons/CameraIcon.tsx
  src/components/Icons/EarthIcon.tsx
  src/components/Icons/LeftArrowIcon.tsx
  src/components/Icons/SettingIcon.tsx
  src/components/Icons/TableIcon.tsx
  src/components/Skeleton/LogCardSkeleton.tsx
  src/components/Skeleton/LogCoverSkeleton.tsx
  src/components/Skeleton/PlaceItemSkeleton.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/skeleton.tsx
  src/contexts/KakaoMap.context.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/CursorBlinker.tsx
  src/features/homepage/LogCard.tsx
  src/features/homepage/MainHero.tsx
  src/features/homepage/TypingText.tsx
  src/features/profile-setting/AccountSettings.tsx
  src/features/profile-setting/DeleteAccountConfirmButton.tsx
  src/features/profile-setting/SaveProfileButton.tsx
  src/features/profile/LogoutButton.tsx
  src/features/profile/LogoutConfirmButton.tsx
  src/hooks/form/useUnsavedChangesWarning.ts
  src/hooks/mutations/user/useDeleteUser.ts
  src/hooks/mutations/user/useLogout.ts
  src/hooks/mutations/user/useUpdateUser.ts
  src/hooks/queries/log/useLog.ts
  src/hooks/queries/log/useLogList.ts
  src/hooks/queries/user/useUser.ts
  src/hooks/useGeolocationPermission.ts
  src/hooks/useImagePreview.ts
  src/hooks/useResponsive.ts
  src/index.css
  src/layouts/RegisterLayout.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/detail/PlacesCollectionPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/profile-setting/index.tsx
  src/pages/register/MapPage.tsx
  src/routes/router.tsx
  src/services/apis/logApi.ts
  src/services/apis/types/logAPI.type.ts
  src/services/apis/types/userAPI.type.ts
  src/services/apis/userApi.ts
Labels: ✨ 기능추가, 🚀 배포, 🎨디자인수정

#50 북마크 API 적용 및 상세 페이지 UI 개선
  index.html
  package.json
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/assets/loadingAnimation.json
  src/components/Loading.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/LogCard.tsx
  src/hooks/useImagePreview.ts
  src/hooks/useImages.ts
  src/pages/detail/DetailPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/register/LogWritePage.tsx
  src/pages/register/MapPage.tsx
  src/services/apis/api.ts
  src/services/apis/logApi.ts
  src/services/apis/placeApi.ts
  src/services/apis/registerApi.ts
  src/store/registerStore.ts
  src/utils/getImgFromCloudFront.ts
  yarn.lock
Labels: ✨ 기능추가, 🎨디자인수정

#51 fix: RefreshToken 만료 시 불필요한 재요청 방지
  src/services/apis/authApi.ts
Labels: 🐛 버그수정

#52 이미지 불러오기, 파비콘 추가 및 토큰 무한요청 버그 수정
  index.html
  package.json
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/assets/loadingAnimation.json
  src/components/Loading.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/LogCard.tsx
  src/hooks/useImagePreview.ts
  src/hooks/useImages.ts
  src/pages/detail/DetailPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/register/LogWritePage.tsx
  src/pages/register/MapPage.tsx
  src/services/apis/api.ts
  src/services/apis/authApi.ts
  src/services/apis/logApi.ts
  src/services/apis/placeApi.ts
  src/services/apis/registerApi.ts
  src/store/registerStore.ts
  src/utils/getImgFromCloudFront.ts
  yarn.lock
Labels: ✨ 기능추가, 🐛 버그수정, 🚀 배포

#53 로그 기능/지도/UI 개선
  package.json
  src/assets/NotFound.png
  src/components/Dialog/ImageDialog.tsx
  src/contexts/KakaoMap.context.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/LogCard.tsx
  src/features/registerpage/CoverImageInput.tsx
  src/features/registerpage/ImagePreviewItem.tsx
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/features/registerpage/PlaceImagesInput.tsx
  src/hooks/mutations/log/useLogBookmarkMutation.ts
  src/hooks/mutations/log/usePlaceBookMarkMutation.ts
  src/hooks/queries/log/logQueryKeys.ts
  src/hooks/queries/log/useLogBookMark.ts
  src/hooks/queries/log/usePlaceBookMark.ts
  src/hooks/useImages.ts
  src/layouts/MainLayout.tsx
  src/pages/Error/NotFoundPage.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/register/LogWritePage.tsx
  src/pages/register/MapPage.tsx
  src/routes/router.tsx
  src/services/apis/logApi.ts
  src/services/apis/placeApi.ts
  src/services/apis/types/placeAPI.type.ts
  src/utils/formatLogForm.ts
  src/utils/imageUtils.ts
  yarn.lock
Labels: ✨ 기능추가, 🎨디자인수정

#54 프로필 페이지 데이터 패칭
  src/components/CustomPagination.tsx
  src/components/Loading.tsx
  src/components/MotionCard.tsx
  src/components/Skeleton/PostCardSkeleton.tsx
  src/components/Skeleton/ProfileHeaderSkeleton.tsx
  src/components/ui/pagination.tsx
  src/features/profile/LogoutButton.tsx
  src/features/profile/PostCard/PostCard.tsx
  src/features/profile/PostCard/PostCardLocation.tsx
  src/features/profile/PostCard/PostCardTitle.tsx
  src/features/profile/PostCard/index.ts
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TapNavigation.tsx
  src/hooks/form/useUnsavedChangesWarning.ts
  src/hooks/mutations/follow/useFollowingMutation.ts
  src/hooks/mutations/follow/useUnfollowMutation.ts
  src/hooks/mutations/user/useUpdateUser.ts
  src/hooks/queries/follow/followQueryKeys.ts
  src/hooks/queries/follow/useFollower.ts
  src/hooks/queries/follow/useFollowing.ts
  src/hooks/queries/follow/useOtherFollower.ts
  src/hooks/queries/follow/useOtherFollowing.ts
  src/hooks/queries/user/useOtherUser.ts
  src/hooks/queries/user/useUser.ts
  src/hooks/queries/user/userQueryKeys.ts
  src/hooks/queries/userLog/useOtherUserBookmarkLogs.ts
  src/hooks/queries/userLog/useOtherUserBookmarkPlaces.ts
  src/hooks/queries/userLog/useOtherUserLogs.ts
  src/hooks/queries/userLog/useUserBookmarkLogs.ts
  src/hooks/queries/userLog/useUserBookmarkPlaces.ts
  src/hooks/queries/userLog/useUserLogs.ts
  src/hooks/queries/userLog/userLogQueryKeys.ts
  src/pages/profile-setting/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/my-logs/index.tsx
  src/pages/profile/saved-logs/index.tsx
  src/pages/profile/saved-spaces/index.tsx
  src/pages/search/index.tsx
  src/services/apis/api.ts
  src/services/apis/followApi.ts
  src/services/apis/types/commonApi.d.ts
  src/services/apis/types/followAPI.d.ts
  src/services/apis/types/userAPI.d.ts
  src/services/apis/types/userLogAPI.d.ts
  src/services/apis/userApi.ts
  src/services/apis/userLogAPI.ts
  src/vite-env.d.ts
Labels: 🔨 리팩토링, ✨ 기능추가

#55 수정 관련 개발
  src/components/Dialog/ConfirmDialog.tsx
  src/components/Drawer/ModifyDrawer.tsx
  src/features/registerpage/LogEditBar.tsx
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/hooks/mutations/log/useDeleteLogMutation.ts
  src/hooks/queries/log/useLog.ts
  src/pages/detail/DetailPage.tsx
  src/pages/register/EditPage.tsx
  src/pages/register/LogWritePage.tsx
  src/pages/register/index.tsx
  src/routes/router.tsx
  src/services/apis/types/registerAPI.type.ts
  src/store/registerStore.ts
Labels: 🔨 리팩토링, ✨ 기능추가

#56 로그 수정 페이지 중간 적용
  src/components/Dialog/ConfirmDialog.tsx
  src/components/Dialog/ImageDialog.tsx
  src/components/ui/carousel.tsx
  src/features/editpage/PlaceEditFormItem.tsx
  src/features/registerpage/CoverImageInput.tsx
  src/features/registerpage/PlaceImagesInput.tsx
  src/pages/detail/DetailPage.tsx
  src/pages/register/EditPage.tsx
  src/services/apis/logApi.ts
  src/services/apis/types/logAPI.type.d.ts
  src/services/apis/types/placeAPI.type.d.ts
  src/services/apis/types/registerAPI.type.d.ts
Labels: ✨ 기능추가

#58 팔로우 관련 기능 추가 및 인증 코드 일부 개선
  src/components/ui/button.tsx
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/profile/ProfileHeader.tsx
  src/hooks/mutations/follow/useFollowingMutation.ts
  src/hooks/mutations/follow/useUnfollowMutation.ts
  src/hooks/queries/follow/useFollower.ts
  src/hooks/queries/follow/useOtherFollower.ts
  src/hooks/queries/user/useOtherUser.ts
  src/hooks/useBottomScrollTrigger.ts
  src/pages/detail/DetailPage.tsx
  src/pages/profile/index.tsx
  src/services/apis/authApi.ts
  src/services/apis/types/userAPI.d.ts
  src/services/apis/userApi.ts
Labels: ✨ 기능추가, 🐛 버그수정

#61 배포 버그 수정 및 팔로워 관련 기능 개선
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/services/apis/userLogApi.ts
Labels: 🐛 버그수정, 🚀 배포

#63 단일로그 응답 변경에 따른 일부 코드 수정
  src/components/CustomPagination.tsx
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/follow/LogFollowingButton.tsx
  src/features/follow/ProfileFollowingButton.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/features/profile/ProfileHeader.tsx
  src/hooks/mutations/follow/useFollowingMutation.ts
  src/hooks/mutations/follow/useUnfollowMutation.ts
  src/hooks/queries/user/useUser.ts
  src/pages/detail/DetailPage.tsx
  src/pages/profile/NotProfileData.tsx
  src/pages/profile/my-logs/index.tsx
  src/pages/profile/saved-logs/index.tsx
  src/pages/profile/saved-spaces/index.tsx
  src/services/apis/types/registerAPI.type.d.ts
Labels: 🔨 리팩토링, ✨ 기능추가

#68 버셀 충돌에러 해결
  src/features/follow/FollowingListButton.tsx
  src/pages/search/index.tsx
  src/services/apis/api.ts
Labels: 🐛 버그수정, 🚀 배포

#71 검색 관련 수정
  src/features/home-page/MainHero.tsx
  src/features/search/CitySearchForm/BnameButtonList.tsx
  src/features/search/CitySearchForm/CitySearchDropbox.tsx
  src/features/search/CitySearchForm/CitySearchForm.tsx
  src/hooks/useKakaoAddressName.ts
  src/hooks/useLocationToAddress.ts
  src/services/data/cityData.ts
  src/store/searchStore.ts
Labels: 🔨 리팩토링

#73 마이페이지, 팔로우, 검색 섹션 버그 수정 및 스타일 추가
  src/components/CustomPagination.tsx
  src/components/GeoConsentModal.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/follow/LogFollowingButton.tsx
  src/features/follow/ProfileFollowingButton.tsx
  src/features/profile/LogoutConfirmButton.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/profile/profileBookMark/SaveLogBookMarkButton.tsx
  src/features/profile/profileBookMark/SavePlaceBookMarkButton.tsx
  src/features/search/CitySearchForm/CitySearchDropbox.tsx
  src/features/search/CitySearchForm/CitySearchForm.tsx
  src/hooks/mutations/follow/useFollowingMutation.ts
  src/hooks/mutations/follow/useUnfollowMutation.ts
  src/hooks/mutations/log/usePlaceBookMarkMutation.ts
  src/hooks/mutations/user/useDeleteUser.ts
  src/hooks/mutations/user/useLogout.ts
  src/hooks/mutations/user/useUpdateUser.ts
  src/hooks/queries/log/logQueryKeys.ts
  src/hooks/queries/log/usePlaceBookMarkCheck.ts
  src/hooks/queries/user/useUser.ts
  src/hooks/useGeolocationPermission.ts
  src/pages/detail-page/index.tsx
  src/pages/profile/my-logs/index.tsx
  src/pages/profile/saved-logs/index.tsx
  src/pages/profile/saved-spaces/index.tsx
  src/services/apis/api.ts
  src/services/apis/authApi.ts
  src/services/apis/placeApi.ts
  src/services/apis/types/placeAPI.type.d.ts
  src/services/apis/userApi.ts
  src/store/geoStore.ts
Labels: ✨ 기능추가, 🐛 버그수정, 🎨디자인수정

#74 Fix/log
  package.json
  src/components/Carousel/MainCarousel.tsx
  src/components/Drawer/ModifyDrawer.tsx
  src/components/LogCard/LogCard.tsx
  src/components/LogCard/ModalLogCard.tsx
  src/features/edit-page/LogCoverEditInput.tsx
  src/features/edit-page/LogEditBar.tsx
  src/features/edit-page/PlacEditFormItem.tsx
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/home-page/MainHero.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/features/register-page/PlaceFormItem.tsx
  src/features/register-page/PlaceImagesInput.tsx
  src/features/register-page/SearchResultDrawer.tsx
  src/hooks/mutations/log/useCreateLogMutation.ts
  src/hooks/mutations/log/useUpdateLogMutation.ts
  src/hooks/queries/log/useLogBookMark.ts
  src/hooks/queries/log/usePlaceBookMark.ts
  src/hooks/queries/user/useAuth.ts
  src/hooks/queries/user/userQueryKeys.ts
  src/hooks/useImagePreview.ts
  src/hooks/useImages.ts
  src/pages/detail-page/components/PlaceItem.tsx
  src/pages/detail-page/index.tsx
  src/pages/edit-page/EditPage.tsx
  src/pages/home/index.tsx
  src/pages/register-page/MapPage.tsx
  src/pages/register-page/index.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/router.tsx
  src/services/apis/logApi.ts
  src/services/apis/registerApi.ts
  src/services/apis/types/registerAPI.type.d.ts
  src/services/schemas/logSchema.ts
  src/store/drawerStore.ts
  src/store/editLogStore.ts
  yarn.lock
Labels: ✨ 기능추가, 🐛 버그수정, 🎨디자인수정

#75 탠스택 쿼리 키 갱신 추가 및 버그 수정
  src/components/Icons/SettingIcon.tsx
  src/features/notification/NotificationButton.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/hooks/mutations/log/useCreateLogMutation.ts
  src/hooks/mutations/user/useDeleteUser.ts
  src/hooks/mutations/user/useLogout.ts
  src/hooks/mutations/user/useUpdateUser.ts
  src/hooks/queries/notification/useNotificationList.ts
  src/services/apis/notificationApi.ts
  src/services/apis/types/notificationAPI.d.ts
Labels: 🔨 리팩토링, 🐛 버그수정

#78 로그 수정페이지 내 버그 수정
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/hooks/useImages.ts
  src/pages/edit-page/EditPage.tsx
  src/store/editLogStore.ts
Labels: ✨ 기능추가, 🐛 버그수정

#79 위치권한 및 수정페이지 버그 수정
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/search/CitySearchForm/CitySearchForm.tsx
  src/hooks/useGeolocationPermission.ts
  src/hooks/useImages.ts
  src/pages/edit-page/EditPage.tsx
  src/pages/profile/index.tsx
  src/store/editLogStore.ts
Labels: 🐛 버그수정, 🚀 배포

#82 유저정보 수정 페이지 이탈 시 alert창 2번 뜨는 현상 해결
  src/pages/profile-setting/index.tsx
Labels: 🐛 버그수정, 🚀 배포

#83 이미지 등록 시 토큰 만료 및 북마크 관련 버그 수정
  src/components/CustomPagination.tsx
  src/components/LogCard/LogCard.tsx
  src/components/Pagination/MainPagination.tsx
  src/features/search/CitySearchForm/CitySearchButton.tsx
  src/features/search/CitySearchForm/CitySearchDropbox.tsx
  src/pages/detail-page/components/MainPageLogCardList.tsx
  src/pages/profile/saved-logs/index.tsx
  src/pages/profile/saved-spaces/index.tsx
  src/pages/search/index.tsx
  src/services/apis/api.ts
Labels: 🐛 버그수정

#85 Fix/빌드 테스트 오류 수정 및 ui 개선
  README.md
  public/fonts/untitled/test-untitled-sans-black-italic.woff2
  public/fonts/untitled/test-untitled-sans-bold-italic.woff2
  public/fonts/untitled/test-untitled-sans-light-italic.woff2
  public/fonts/untitled/test-untitled-sans-medium-italic.woff2
  public/fonts/untitled/test-untitled-sans-regular-italic.woff2
  src/components/Dialog/ImageDialog.tsx
  src/components/LogCard/LogCard.tsx
  src/components/LogCard/ModalLogCard.tsx
  src/constants/selections.ts
  src/features/edit-page/LogCoverEditInput.tsx
  src/features/edit-page/PlacEditFormItem.tsx
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/home-page/CourseButton.tsx
  src/features/home-page/MainHero.tsx
  src/features/home-page/TypingText.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/features/register-page/CoverImageInput.tsx
  src/features/register-page/LogCoverImgInput.tsx
  src/features/register-page/OptionEditSection.tsx
  src/features/register-page/OptionSelection.tsx
  src/features/register-page/PlaceImagesInput.tsx
  src/hooks/mutations/log/useCreateLogMutation.ts
  src/hooks/mutations/log/useDeleteLogMutation.ts
  src/hooks/mutations/log/useUpdateLogMutation.ts
  src/hooks/queries/log/logQueryKeys.ts
  src/hooks/useImagePreview.ts
  src/hooks/useImages.ts
  src/index.css
  src/layouts/EditLayout.tsx
  src/pages/detail-page/PlacesCollectionPage.tsx
  src/pages/detail-page/components/MainPageLogCardList.tsx
  src/pages/detail-page/index.tsx
  src/pages/edit-page/index.tsx
  src/pages/home/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/pages/register-page/MapPage.tsx
  src/pages/register-page/SelectPage.tsx
  src/routes/router.tsx
  src/services/apis/logApi.ts
  src/services/apis/placeApi.ts
  src/services/apis/registerApi.ts
  src/services/apis/types/logAPI.type.d.ts
  src/services/apis/types/registerAPI.type.d.ts
  src/store/registerStore.ts
  src/utils/resizeImageToWebp.ts
  tailwind.config.js
Labels: 🔨 리팩토링, ✨ 기능추가, 🐛 버그수정, 🎨디자인수정

#86 검색 페이지 UI 수정, 마이페이지 fallback 추가 및 위치 권한 모달 개선
  src/components/CustomPagination.tsx
  src/components/GeoConsentModal.tsx
  src/components/Header/SectionHeader.tsx
  src/features/profile/PostCard/index.ts
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TapNavigation.tsx
  src/features/profile/fallback/ProfileFallbackMessage.tsx
  src/features/profile/fallback/ProfileMyLogFallback.tsx
  src/features/search/SearchTitleHeader.tsx
  src/layouts/RegisterLayout.tsx
  src/pages/profile/my-logs/index.tsx
  src/pages/profile/saved-logs/index.tsx
  src/pages/profile/saved-spaces/index.tsx
  src/pages/search/index.tsx
Labels: ✨ 기능추가, 🐛 버그수정, 🎨디자인수정

#87 fix : edit 페이지 라우트 변경
  src/pages/detail-page/index.tsx
  src/routes/router.tsx
  src/services/apis/types/registerAPI.type.d.ts
Labels: 🎨디자인수정

#89 프로필페이지 관련 버그 수정
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/follow/LogFollowingButton.tsx
  src/features/follow/ProfileFollowingButton.tsx
  src/features/profile/ProfileHeader.tsx
  src/pages/profile-setting/index.tsx
  src/pages/profile/my-logs/index.tsx
Labels: 🔨 리팩토링, 🐛 버그수정

#91 Fix/ 최근 검색 부분 수정
  src/pages/register-page/SearchPage.tsx
  src/store/registerStore.ts
Labels: 🐛 버그수정

#92 회원정보 수정 얼럿창 버그 및 알림 상대시간 수정
  package.json
  src/components/Header/SectionHeader.tsx
  src/features/follow/ProfileFollowingButton.tsx
  src/features/notification/NotificationButton.tsx
  src/features/notification/NotificationItem.tsx
  src/features/profile/ProfileHeader.tsx
  src/hooks/form/useUnsavedChangesWarning.ts
  src/pages/profile-setting/index.tsx
  src/store/profileStore.ts
  src/utils/timeUtils.ts
  yarn.lock
Labels: ✨ 기능추가, 🐛 버그수정

#93 프로필수정 페이지 버그 수정
  src/features/profile-setting/ProfileSettingAvatar.tsx
  src/hooks/form/useUnsavedChangesWarning.ts
  src/hooks/mutations/user/useUpdateUser.ts
  src/pages/profile-setting/index.tsx
  src/services/apis/types/userAPI.d.ts
  src/store/profileStore.ts
Labels: 🚀 배포

#94 프로필 저장 후에도 경고창이 뜨는 문제 해결
  src/features/profile-setting/SaveProfileButton.tsx
  src/pages/profile-setting/index.tsx
  src/store/profileStore.ts
Labels: 🐛 버그수정

#96 Develop
  index.html
  package.json
  public/manifest.json
  src/components/Header/SectionHeader.tsx
  src/features/edit-page/LogCoverEditInput.tsx
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/follow/ProfileFollowingButton.tsx
  src/features/notification/NotificationButton.tsx
  src/features/notification/NotificationItem.tsx
  src/features/profile-setting/ProfileSettingAvatar.tsx
  src/features/profile-setting/SaveProfileButton.tsx
  src/features/profile/ProfileHeader.tsx
  src/features/register-page/CoverImageInput.tsx
  src/features/register-page/LogCoverImgInput.tsx
  src/features/register-page/PlaceImagesInput.tsx
  src/hooks/form/useUnsavedChangesWarning.ts
  src/hooks/mutations/user/useUpdateUser.ts
  src/pages/profile-setting/index.tsx
  src/pages/register-page/SearchPage.tsx
  src/services/apis/types/userAPI.d.ts
  src/store/profileStore.ts
  src/store/registerStore.ts
  src/utils/timeUtils.ts
  yarn.lock
Labels: 🚀 배포

#97 수정 사항 개선
  public/fonts/untitled/test-untitled-sans-medium.woff2
  src/components/Carousel/MainCarousel.tsx
  src/features/home-page/MainHero.tsx
  src/features/home-page/TypingText.tsx
  src/features/register-page/RegisterSearchBar.tsx
  src/features/register-page/SearchResultDrawer.tsx
  src/features/search/CitySearchForm/CitySearchForm.tsx
  src/index.css
  src/pages/edit-page/index.tsx
  src/pages/home/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/services/schemas/logSchema.ts
  tailwind.config.js
Labels: 🎨디자인수정

#98 공지사항 헤더 모션 수정 및 텍스트 스타일 개선
  src/components/CustomPagination.tsx
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
  src/components/Header/SectionHeader.tsx
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/login/LoginModal.tsx
  src/features/notice/notice-detail/NoticeDetailContent.tsx
  src/features/notice/notice-detail/NoticeDetailHeader.tsx
  src/features/profile-setting/AccountSettings.tsx
  src/features/profile-setting/DeleteAccountConfirmButton.tsx
  src/features/profile-setting/SaveProfileButton.tsx
  src/features/profile/FollowButton.tsx
  src/features/profile/LogoutButton.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/profile/PostCard/PostCardLocation.tsx
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TabNavButton.tsx
  src/features/search/SearchNotFound.tsx
  src/features/search/SearchTitleHeader.tsx
  src/index.css
  src/pages/notice/index.tsx
  src/pages/notice/notice-detail/index.tsx
  src/pages/profile-setting/index.tsx
Labels: 🎨디자인수정

#99 Develop
  public/fonts/untitled/test-untitled-sans-medium.woff2
  src/components/Carousel/MainCarousel.tsx
  src/components/CustomPagination.tsx
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
  src/components/Header/SectionHeader.tsx
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/home-page/MainHero.tsx
  src/features/home-page/TypingText.tsx
  src/features/login/LoginModal.tsx
  src/features/notice/notice-detail/NoticeDetailContent.tsx
  src/features/notice/notice-detail/NoticeDetailHeader.tsx
  src/features/profile-setting/AccountSettings.tsx
  src/features/profile-setting/DeleteAccountConfirmButton.tsx
  src/features/profile-setting/SaveProfileButton.tsx
  src/features/profile/FollowButton.tsx
  src/features/profile/LogoutButton.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/profile/PostCard/PostCardLocation.tsx
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TabNavButton.tsx
  src/features/register-page/RegisterSearchBar.tsx
  src/features/register-page/SearchResultDrawer.tsx
  src/features/search/CitySearchForm/CitySearchForm.tsx
  src/features/search/SearchNotFound.tsx
  src/features/search/SearchTitleHeader.tsx
  src/index.css
  src/pages/edit-page/index.tsx
  src/pages/home/index.tsx
  src/pages/notice/index.tsx
  src/pages/notice/notice-detail/index.tsx
  src/pages/profile-setting/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/services/schemas/logSchema.ts
  tailwind.config.js
Labels: 🚀 배포

#100 검색 폰트 및 검색결과 없음 컴포넌트 수정
  src/components/Header/SectionHeader.tsx
  src/features/search/SearchTitleHeader.tsx
  src/pages/search/index.tsx
Labels: 🔨 리팩토링, 🎨디자인수정
