Repository spoteditor/Spoteditor-Frontend, pull requests merged in 2025-04, with the labels that each got.

#102 소셜 로그인 로그인 리다이렉트 수정 및 배포환경 콘솔로그 삭제
  package.json
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
  src/features/login/KakaoLoginButton.tsx
  src/services/apis/authApi.ts
  vite.config.ts
  yarn.lock
Labels: ⚙️ 개발환경, ✨ 기능추가

#103 구글 로그인 추가
  src/assets/login/google-login-button.png
  src/assets/login/kakao-login-button.png
  src/assets/profile/user-default-avatar.png
  src/features/login/KakaoLoginButton.tsx
  src/features/login/LoginModal.tsx
  src/features/login/SocialLoginButtons/SocialLoginButton.tsx
  src/features/login/SocialLoginButtons/SocialLoginButtons.tsx
  src/services/apis/userApi.ts
  src/vite-env.d.ts
Labels: ✨ 기능추가

#104 검색 페이지, 로그인 기능 및 소셜 로그인 개선 반영
  package.json
  src/assets/login/google-login-button.png
  src/assets/login/kakao-login-button.png
  src/assets/profile/user-default-avatar.png
  src/components/Footer/MainFooter.tsx
  src/components/Header/MainHeader/components/LoginStatusButtons.tsx
  src/components/Header/MainHeader/components/UserProfileButton/MyProfileButton.tsx
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
  src/components/Header/SectionHeader.tsx
  src/features/login/KakaoLoginButton.tsx
  src/features/login/LoginModal.tsx
  src/features/login/SocialLoginButtons/SocialLoginButton.tsx
  src/features/login/SocialLoginButtons/SocialLoginButtons.tsx
  src/features/notification/NotificationButton.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/features/profile/ProfileHeader.tsx
  src/features/search/SearchTitleHeader.tsx
  src/hooks/queries/log/useLogBookMark.ts
  src/hooks/queries/log/usePlaceBookMark.ts
  src/hooks/queries/user/useAuth.ts
  src/hooks/queries/user/useUser.ts
  src/pages/detail-page/index.tsx
  src/pages/profile-setting/index.tsx
  src/pages/profile/my-logs/index.tsx
  src/pages/profile/saved-logs/index.tsx
  src/pages/profile/saved-spaces/index.tsx
  src/pages/search/index.tsx
  src/routes/ProtectedRoute.tsx
  src/services/apis/authApi.ts
  src/services/apis/userApi.ts
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: 🚀 배포

#105 콘솔 로그가 개발 환경에서도 사라지는 문제 해결
  src/main.tsx
  vite.config.ts
Labels: 🐛 버그수정

#106 등록, 수정, 헤더 리팩토링
  index.html
  package.json
  src/assets/homepage/logo.png
  src/assets/homepage/search.png
  src/assets/homepage/signup.png
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Header/MainHeader/components/LoginButton.tsx
  src/components/Icons/LogoIcon.tsx
  src/components/LogCard/LogCard.tsx
  src/components/LogCard/ModalLogCard.tsx
  src/components/ScrollToTop.tsx
  src/components/ui/textarea.tsx
  src/contexts/KakaoMap.context.tsx
  src/features/edit-page/LogCoverEditInput.tsx
  src/features/edit-page/PlacEditFormItem.tsx
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/login/LoginModal.tsx
  src/features/register-page/LogCoverImgInput.tsx
  src/features/register-page/LogWriteBar.tsx
  src/features/register-page/PlaceFormItem.tsx
  src/features/register-page/PlaceImagesInput.tsx
  src/features/register-page/RegisterSearchBar.tsx
  src/hooks/useFormattedLog.ts
  src/hooks/useImageUpload.ts
  src/hooks/useImagesUpload.ts
  src/layouts/ContentLayout.tsx
  src/layouts/MainLayout.tsx
  src/pages/detail-page/components/PlaceItem.tsx
  src/pages/detail-page/index.tsx
  src/pages/edit-page/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/routes/ProtectedRoute.tsx
  src/store/loginStore.ts
  src/utils/compressImage.ts
  src/utils/getPresignedUrls.ts
  src/utils/resizeImageToWebp.ts
  tailwind.config.js
  yarn.lock
Labels: 🔨 리팩토링, 🎨디자인수정

#107 Develop
  index.html
  package.json
  src/assets/homepage/logo.png
  src/assets/homepage/search.png
  src/assets/homepage/signup.png
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Header/MainHeader/components/LoginButton.tsx
  src/components/Icons/LogoIcon.tsx
  src/components/LogCard/LogCard.tsx
  src/components/LogCard/ModalLogCard.tsx
  src/components/ScrollToTop.tsx
  src/components/ui/textarea.tsx
  src/contexts/KakaoMap.context.tsx
  src/features/edit-page/LogCoverEditInput.tsx
  src/features/edit-page/PlacEditFormItem.tsx
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/login/LoginModal.tsx
  src/features/register-page/LogCoverImgInput.tsx
  src/features/register-page/LogWriteBar.tsx
  src/features/register-page/PlaceFormItem.tsx
  src/features/register-page/PlaceImagesInput.tsx
  src/features/register-page/RegisterSearchBar.tsx
  src/hooks/useFormattedLog.ts
  src/hooks/useImageUpload.ts
  src/hooks/useImagesUpload.ts
  src/layouts/ContentLayout.tsx
  src/layouts/MainLayout.tsx
  src/main.tsx
  src/pages/detail-page/components/PlaceItem.tsx
  src/pages/detail-page/index.tsx
  src/pages/edit-page/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/routes/ProtectedRoute.tsx
  src/store/loginStore.ts
  src/utils/compressImage.ts
  src/utils/getPresignedUrls.ts
  src/utils/resizeImageToWebp.ts
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: 🚀 배포

#111 모달관련 버그수정과 나의 로그 낙관적 업데이트 적용 및 UI 개선
  src/components/GeoConsentModal.tsx
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Header/MainHeader/components/UserProfileButton/UserProfileButton.tsx
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/follow/ProfileFollowingButton.tsx
  src/features/home-page/MainHero.tsx
  src/features/profile-setting/SaveProfileButton.tsx
  src/features/profile/OtherUserProfileSection.tsx
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TapNavigation.tsx
  src/features/search/CitySearchForm/CitySearchDropbox.tsx
  src/features/search/CitySearchForm/CitySearchForm.tsx
  src/hooks/mutations/log/useLogBookmarkMutation.ts
  src/hooks/mutations/log/usePlaceBookMarkMutation.ts
  src/services/data/cityData.ts
  src/store/searchStore.ts
Labels: 🚀 배포

#112 Develop
  src/components/Footer/MainFooter.tsx
  src/components/LogCard/LogCard.tsx
  src/components/LogCard/ModalLogCard.tsx
  src/features/home-page/MainHero.tsx
  src/features/profile/LogAuthorInfo.tsx
  src/features/search/CitySearchForm/CitySearchForm.tsx
  src/index.css
  src/pages/detail-page/index.tsx
  tailwind.config.js
Labels: 🚀 배포

#113 ui 수정 및 리팩토링
  package.json
  src/components/Carousel/MainCarousel.tsx
  src/components/Dialog/ImageDialog.tsx
  src/components/Drawer/ModifyDrawer.tsx
  src/components/Icons/HomeIcon.tsx
  src/components/Icons/index.ts
  src/components/LogCard/LogCard.tsx
  src/components/LogCard/ModalLogCard.tsx
  src/components/Toggle/PrivateToggle.tsx
  src/components/ui/switch.tsx
  src/features/edit-page/LogEditBar.tsx
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/profile/TapNavigation.tsx
  src/features/register-page/ImagePreviewItem.tsx
  src/features/register-page/PlaceImagesInput.tsx
  src/features/register-page/RegisterBar.tsx
  src/features/search/SearchTitleHeader.tsx
  src/hooks/useFormattedLog.ts
  src/pages/detail-page/index.tsx
  src/pages/edit-page/index.tsx
  src/pages/home/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/pages/register-page/SelectPage.tsx
  src/pages/search/index.tsx
  src/services/apis/types/registerAPI.type.d.ts
  src/services/schemas/logSchema.ts
  src/store/editLogStore.ts
  src/utils/compressImage.ts
  src/utils/formatLogForm.ts
  yarn.lock
Labels: 🔨 리팩토링, 🎨디자인수정

#114 북마크 관련 버그 수정 및 프로필 관련 ui 개선
  src/assets/profile/user-default-avatar.png
  src/assets/profile/user-default-avatar.webp
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/profile/LogAuthorInfo.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/profile/ProfileHeader.tsx
  src/hooks/mutations/log/useLogBookmarkMutation.ts
  src/pages/profile-setting/index.tsx
  src/services/apis/userApi.ts
Labels: 🐛 버그수정, 🎨디자인수정

#115 Deploy
  package.json
  src/assets/profile/user-default-avatar.png
  src/assets/profile/user-default-avatar.webp
  src/components/Carousel/MainCarousel.tsx
  src/components/Dialog/ImageDialog.tsx
  src/components/Drawer/ModifyDrawer.tsx
  src/components/Icons/HomeIcon.tsx
  src/components/Icons/index.ts
  src/components/LogCard/LogCard.tsx
  src/components/LogCard/ModalLogCard.tsx
  src/components/Toggle/PrivateToggle.tsx
  src/components/ui/switch.tsx
  src/features/edit-page/LogEditBar.tsx
  src/features/edit-page/PlaceEditImagesInput.tsx
  src/features/follow/FollowerListButton.tsx
  src/features/follow/FollowingListButton.tsx
  src/features/profile/LogAuthorInfo.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TapNavigation.tsx
  src/features/register-page/ImagePreviewItem.tsx
  src/features/register-page/PlaceImagesInput.tsx
  src/features/register-page/RegisterBar.tsx
  src/features/search/SearchTitleHeader.tsx
  src/hooks/mutations/log/useLogBookmarkMutation.ts
  src/hooks/useFormattedLog.ts
  src/pages/detail-page/index.tsx
  src/pages/edit-page/index.tsx
  src/pages/home/index.tsx
  src/pages/profile-setting/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/pages/register-page/SelectPage.tsx
  src/pages/search/index.tsx
  src/services/apis/types/registerAPI.type.d.ts
  src/services/apis/userApi.ts
  src/services/schemas/logSchema.ts
  src/store/editLogStore.ts
  src/utils/compressImage.ts
  src/utils/formatLogForm.ts
  yarn.lock
Labels: 🚀 배포

#116 ui 수정 및 컴포넌트 분리
  src/components/Button/FloatingButton.tsx
  src/components/Header/CaptionTitle.tsx
  src/components/Header/SectionHeader.tsx
  src/components/Icons/HomeIcon.tsx
  src/features/profile/LogAuthorInfo.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/search/SearchNotFound.tsx
  src/features/search/SearchTitleHeader.tsx
  src/layouts/ContentLayout.tsx
  src/layouts/EditLayout.tsx
  src/layouts/PageLayout.tsx
  src/layouts/RegisterLayout.tsx
  src/pages/detail-page/PlacesCollectionPage.tsx
  src/pages/detail-page/components/BannerActionButtons.tsx
  src/pages/detail-page/components/DetailBanner.tsx
  src/pages/detail-page/index.tsx
  src/pages/home/components/MainPageLogCardList.tsx
  src/pages/home/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/pages/register-page/SelectPage.tsx
  src/pages/search/index.tsx
Labels: 🔨 리팩토링, 🎨디자인수정

#117 Develop
  src/components/Button/FloatingButton.tsx
  src/components/Header/CaptionTitle.tsx
  src/components/Header/SectionHeader.tsx
  src/components/Icons/HomeIcon.tsx
  src/features/profile/LogAuthorInfo.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/search/SearchNotFound.tsx
  src/features/search/SearchTitleHeader.tsx
  src/layouts/ContentLayout.tsx
  src/layouts/EditLayout.tsx
  src/layouts/PageLayout.tsx
  src/layouts/RegisterLayout.tsx
  src/pages/detail-page/PlacesCollectionPage.tsx
  src/pages/detail-page/components/BannerActionButtons.tsx
  src/pages/detail-page/components/DetailBanner.tsx
  src/pages/detail-page/index.tsx
  src/pages/home/components/MainPageLogCardList.tsx
  src/pages/home/index.tsx
  src/pages/register-page/LogWritePage.tsx
  src/pages/register-page/SelectPage.tsx
  src/pages/search/index.tsx
Labels: 🚀 배포
