Repository spoteditor/Spoteditor-Frontend, pull requests merged in 2025-02, with the labels that each got.

#10 알림 기능 추가
  package.json
  src/components/Header/MainHeader/LoginStatusButtons.tsx
  src/components/Icons/EmptyIcon.tsx
  src/components/Icons/XIcon.tsx
  src/components/ui/sheet.tsx
  src/feature/notification/NotNotification.tsx
  src/feature/notification/NotificationButton.tsx
  yarn.lock
Labels: ✨ 기능추가

#11 검색창 오버레이 관련 버그 수정
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/SearchBar/SearchBar.tsx
  src/feature/login/LoginModal.tsx
Labels: 🐞 버그수정

#13 build.sh 파일 추가
  build.sh
Labels: 🚀 배포

#14 사용되지 않은 코드 삭제
  src/components/CustomPagination.tsx
  src/components/ui/sheet.tsx
  src/feature/homepage/SortByLog.tsx
  src/feature/profile/FollowButton.tsx
  src/pages/search/index.tsx
Labels: 🐛 버그수정

#18 Merge Develop branch into Main
  package.json
  src/components/Header/MainHeader/LoginStatusButtons.tsx
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Header/MainHeader/UserProfileButton.tsx
  src/components/Header/SectionHeader.tsx
  src/components/Icons/BookMarkIcon.tsx
  src/components/Icons/ClockIcon.tsx
  src/components/Icons/SpotIcon.tsx
  src/components/Icons/StarIcon.tsx
  src/components/Icons/SubstractIcon.tsx
  src/components/Icons/SubtractIcon.tsx
  src/components/Icons/TableIcon.tsx
  src/components/Icons/index.ts
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/components/ui/dialog.tsx
  src/features/detailpage/PlaceItem.tsx
  src/features/homepage/LogCard.tsx
  src/features/homepage/PlaceCard.tsx
  src/features/login/LoginModal.tsx
  src/features/notification/NotNotification.tsx
  src/features/notification/NotificationButton.tsx
  src/features/profile-setting/DeleteAccountConfirmButton.tsx
  src/features/profile-setting/SaveProfileButton.tsx
  src/features/profile/FollowButton.tsx
  src/features/profile/PostCard/PostCard.tsx
  src/features/profile/PostCard/PostCardImage.tsx
  src/features/profile/PostCard/PostCardLocation.tsx
  src/features/profile/PostCard/PostCardTitle.tsx
  src/features/profile/PostCard/PostCardWrapper.tsx
  src/features/profile/PostCard/index.ts
  src/features/profile/ProfileHeader.tsx
  src/features/profile/TapNavigation.tsx
  src/features/search/SearchBar.tsx
  src/features/search/SearchNotFound.tsx
  src/layouts/MainLayout.tsx
  src/layouts/PageLayout.tsx
  src/pages/detail/index.tsx
  src/pages/home/index.tsx
  src/pages/profile-setting/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/my-logs/index.tsx
  src/pages/profile/saved-logs/index.tsx
  src/pages/profile/saved-spaces/index.tsx
  src/pages/search/index.tsx
  tailwind.config.js
  yarn.lock
Labels: 🚀 배포

#21 공지사항 페이지 및 공지사항 상세 페이지 추가
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Header/MainHeader/UserProfileButton.tsx
  src/components/Icons/LeftArrowIcon.tsx
  src/components/Icons/SettingIcon.tsx
  src/components/ui/dialog.tsx
  src/features/login/LoginModal.tsx
  src/features/notice/NoticeHeader.tsx
  src/features/notice/notice-detail/NoticeDetailContent.tsx
  src/features/notice/notice-detail/NoticeDetailHeader.tsx
  src/features/notice/notice-detail/NoticeDetailInfo.tsx
  src/features/profile/FollowButton.tsx
  src/features/profile/LogoutButton.tsx
  src/features/search/SearchBar.tsx
  src/layouts/MainLayout.tsx
  src/pages/notice/index.tsx
  src/pages/notice/notice-detail/index.tsx
  src/routes/router.tsx
Labels: ✨ 기능추가

#22 페이지네이션 타입 오류 수정 및 불필요한 React import 제거
  src/components/Icons/StarIcon.tsx
  src/components/Icons/TableIcon.tsx
  src/components/ui/pagination.tsx
Labels: 🐛 버그수정, 🚀 배포

#23 프로필 설정 페이지 리팩토링 및 이미지 업로드 기능 추가
  src/components/Header/MainHeader/UserProfileButton.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/features/profile-setting/AccountSettings.tsx
  src/features/profile-setting/DeleteAccountConfirmButton.tsx
  src/features/profile-setting/ProfileSettingAvatar.tsx
  src/features/profile-setting/ProfileSettingForm.tsx
  src/features/profile-setting/SaveProfileButton.tsx
  src/features/profile/LogoutButton.tsx
  src/features/profile/ProfileHeader.tsx
  src/hooks/useImagePreview.tsx
  src/pages/profile-setting/index.tsx
  src/services/schemas/profileSchema.ts
Labels: 🔨 리팩토링, ✨ 기능추가

#24 카카오 로그인 기능 추가
  .gitignore
  src/features/login/KakaoLoginButton.tsx
  src/features/login/LoginModal.tsx
  src/hooks/useUser.tsx
  src/services/apis/authApi.ts
  src/services/apis/userApi.ts
  src/vite-env.d.ts
Labels: ✨ 기능추가

#25 등록 페이지 퍼블리싱 및 카카오맵 기능 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/refactor_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/main.yml
  index.html
  public/fonts/untitled/test-untitled-sans-black-italic.woff2
  public/fonts/untitled/test-untitled-sans-black.woff2
  public/fonts/untitled/test-untitled-sans-bold-italic.woff2
  public/fonts/untitled/test-untitled-sans-bold.woff2
  public/fonts/untitled/test-untitled-sans-light-italic.woff2
  public/fonts/untitled/test-untitled-sans-light.woff2
  public/fonts/untitled/test-untitled-sans-medium-italic.woff2
  public/fonts/untitled/test-untitled-sans-regular-italic.woff2
  public/fonts/untitled/test-untitled-sans-regular.woff2
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/ui/button.tsx
  src/components/ui/textarea.tsx
  src/constants/pathname.ts
  src/features/homepage/CitySearchForm.tsx
  src/features/homepage/MainHero.tsx
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/features/registerpage/PlaceListItem.tsx
  src/features/registerpage/RegisterSearchBar.tsx
  src/fonts/TestUntitledSans-Light.otf
  src/index.css
  src/layouts/MainLayout.tsx
  src/layouts/RegisterLayout.tsx
  src/pages/home/index.tsx
  src/pages/register/DetailsPage.tsx
  src/pages/register/MapPage.tsx
  src/pages/register/SearchPage.tsx
  src/pages/register/SelectPage.tsx
  src/pages/register/index.tsx
  src/routes/router.tsx
  tailwind.config.js
Labels: ✨ 기능추가

#26 검색창 모션 및 위치 권한 요청 모달창 추가
  src/components/GeoConsentModal.tsx
  src/components/Header/MainHeader/MainHeader.tsx
  src/components/Icons/CompassIcon.tsx
  src/features/login/LoginModal.tsx
  src/features/search/SearchBar.tsx
  src/layouts/MainLayout.tsx
  src/pages/search/index.tsx
Labels: ✨ 기능추가, 🐛 버그수정

#28 등록 페이지 추가 퍼블리싱 및 지도 기능 수정
  index.html
  src/components/ui/button.tsx
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/features/registerpage/PlaceListItem.tsx
  src/features/registerpage/RegisterSearchBar.tsx
  src/layouts/RegisterLayout.tsx
  src/pages/register/DetailsPage.tsx
  src/pages/register/MapPage.tsx
  src/pages/register/NewPlacePage.tsx
  src/pages/register/SearchPage.tsx
  src/pages/register/SelectPage.tsx
  src/pages/register/index.tsx
  src/pages/register/types/Place.type.ts
  src/routes/router.tsx
  src/store/registerStore.ts
Labels: 🔨 리팩토링, ✨ 기능추가

#31 카카오맵 타입 적용 문제로 배포 안 되는 버그
  package.json
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/features/registerpage/PlaceListItem.tsx
  src/pages/register/MapPage.tsx
  src/pages/register/SearchPage.tsx
  src/pages/register/types/Place.type.ts
  src/store/registerStore.ts
  src/store/store.ts
  src/types/global.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🐛 버그수정, 🚀 배포

#32 api 연결전 등록 과정 구현
  package.json
  src/components/ui/alert-dialog.tsx
  src/components/ui/drawer.tsx
  src/features/profile-setting/ProfileSettingAvatar.tsx
  src/features/profile/TapNavigation.tsx
  src/features/registerpage/ImagePreviewItem.tsx
  src/features/registerpage/PlaceDetailFormItem.tsx
  src/features/registerpage/SearchPlacesDrawer.tsx
  src/hooks/useImagePreview.tsx
  src/hooks/useImages.tsx
  src/pages/home/index.tsx
  src/pages/register/DetailsPage.tsx
  src/pages/register/MapPage.tsx
  yarn.lock
Labels: ✨ 기능추가

#33 로컬 개발 환경 https 적용
  .gitignore
  src/services/apis/authApi.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: ⚙️ 개발환경
